version: '2'
services:
  builder:
    build: builder
    volumes:
      - webapps:/webapps
  prod:
    image: tomcat:jre8-openjdk-slim
    ports:
      - "8081:8080"
    volumes:
      - webapps:/usr/local/tomcat/webapps
volumes:
  webapps: